#!/usr/bin/env python
src = '/home/searene/Development/ImageResizer/ImageResizer.py'
target = '/home/searene/Documents/Anki/addons/ImageResizer.py'
configPickle = '/home/searene/Documents/Anki/addons/ImageResizer/config.pickle'

# copy if the files are not identical or the target file doesn't exist
import filecmp
import shutil
import os
if not os.path.exists(target):
    open(target, 'a').close()
if not filecmp.cmp(src, target):
    shutil.copyfile(src, target)

# delete config.pickle if it exists
if os.path.exists(configPickle):
    os.remove(configPickle)

# insert anki development package
import sys
anki = os.path.join('/home/searene/Development/anki')
sys.path.insert(0, anki)

# run anki
import aqt
aqt.run()
